# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Helpful Rabbit
tagline:          'Personal blog of Vijay Nandwani'
description:      'Blog posts by <a href="twitter.com/isthegeek">Vijay Nandwani</a>'
url:              http://twitter.com/isthegeek
baseurl:          /

author:
  name:           'Vijay Nandwani'
  url:            https://twitter.com/isthegeek

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
